@startuml

skinparam classAttributeIconSize 0

class Transaction {
    products: Product[]
    addProduct(Product product): void
    calculateTotal(): int
}

class Product {
    -name: String
    -price: int
    << create >> +Product(name: String, price: int)
    +getName(): String
    +getPrice(): int
}

class ProductTransaction {
    -quantity: int
    -discount: int
    +getQuantity(): int
    +setQuantity(): void
    +getDiscount(): int
    +setDiscount(): void
    +getTotalPrice(): int
}
Product <|-- ProductTransaction
Transaction -- ProductTransaction

@enduml
